on:
  workflow_call:
    inputs:
      Environment:
        required: true
        type: string
      region:
        required: true
        type: string    
         
    secrets:
      role:
        required: true
 
permissions:
    id-token: write
    contents: read
 
jobs:
  linting:
    if: github.event.pull_request.merged == true
    environment:  ${{ inputs.Environment }}
    name: Linting ${{ inputs.Environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Setup Cloud Formation Linter with Latest Version
      uses: scottbrenner/cfn-lint-action@v2
 
    - name: Run Cloud Formation Linter
      run: cfn-lint -t ./cfn_template.yaml
 
  deploy:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.Environment }}
    needs: linting
    name: Deploy to ${{ inputs.Environment }}
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role }}
          aws-region: ${{ inputs.region }}
          
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "public-hosted-s3-${{ inputs.Environment }}"
          template: ${{ github.workspace }}/cfn_template.yml
          parameter-overrides: >-
            Environment=${{ inputs.Environment }}
          capabilities: CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND
          no-fail-on-empty-changeset: "1"