name: Dev Deployment
 
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
     
jobs:
 dev-pipeline:
  uses: ./.github/workflows/deploy.yml
  with:
      Environment: dev
      region: us-east-1
 
  secrets:
      role: ${{ secrets.DEPLOYMENT_ROLE }}