name: Qa Deployment
 
on:
  pull_request:
    types:
      - closed
    branches:
      - qa
 
jobs:
 qa-pipeline:
  uses: ./.github/workflows/deploy.yml
  with:
      Environment: qa
      region: us-east-1
 
  secrets:
      role: ${{ secrets.DEPLOYMENT_ROLE }}