AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Sample Cloudformation Template to validate pipeline
Parameters:
  Environment:
    Type: String
    Description: Account environment the stack is being deployed
    AllowedValues:
      - dev
      - qa
      - prod

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      VersioningConfiguration:
           Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
        - Key: Environment
          Value: !Ref Environment

