# .github/workflows/validate.yml
name: Validate Templates

on:
  pull_request:
    paths:
      - 'templates/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup cfn-lint
        run: pip install cfn-lint
      
      - name: Validate Templates
        run: |
          for template in templates/**/*.yaml; do
            echo "Validating $template"
            cfn-lint $template
            aws cloudformation validate-template \
              --template-body file://$template
          done